# Generated by Django 3.0.4 on 2020-03-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceOrders',
            new_name='ServiceOrder',
        ),
    ]
