# Generated by Django 3.0.4 on 2020-04-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_auto_20200405_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceservice',
            name='name',
            field=models.CharField(default='migrated resource service', max_length=255),
            preserve_default=False,
        ),
    ]
