# Generated by Django 3.0.4 on 2020-04-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_resourceservice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='speed',
        ),
    ]
